### DISCUSSION TITLE
How to pass env values to apiman.properties ( apiman UI )  & conf-es.config ( vertx gateway )

### DISCUSSION THREAD

**Discussion by iamakashk** [apiman/apiman#1663] [Help] [answered]
Hi 

I need a suggestion to make apiman.properties ( apiman ui ) & conf-es.config ( vertx gateway ) values dynamic using docker compose env. 

apiman.properties
```
apiman.es.protocol=http
apiman.es.host=IP
apiman.es.port=8000
apiman.es.username=elastic
apiman.es.password=changeme
apiman.es.timeout=10000
```

conf-es.config

```

 "variables": {
    "apiman": {
      "es": {
       "protocol": "http",
        "host": "IP",
        "port": 8000,
        "username": "elastic",
        "password": "changeme",
        "timeout": 10000,
        "pollingTime": 600
        // only for https
        //"allowSelfSigned": false,
        //"allowAnyHost": false,
        //"truststore": {
        //  "path": "/usr/src/apiman/apiman-distro-vertx/apiman.jks",
        //  "password": "secret"
        //},
        //"keystore": {
        //  "path": "/usr/src/apiman/apiman-distro-vertx/apiman.jks",
        //  "password": "secret"
        //}
      }
    }
  }
```

Following is the dockerfile : 

```
FROM  jboss/wildfly:20.0.0.Final
MAINTAINER Marc Savy <marc@rhymewithgravy.com>

COPY  ui-manager_2.1 ${JBOSS_HOME}

USER root

RUN chown -R jboss:0 ${JBOSS_HOME} \
 && chmod -R g+rw ${JBOSS_HOME}

USER jboss


# Set the default command to run on boot
ENTRYPOINT ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0", "-c", "standalone-apiman.xml"]

```

Docker compose file : 

```
version: "3"
services:
  api-manager-ui:
    image: mycustomimage
    container_name: api-manager-ui
    network_mode: "host"
    expose:
      - "9990"
      - "9993"
      - "8009"
      - "8080"
      - "8443"
    ports:
      - "9990:9990"
      - "9993:9993"
      - "8009:8009"
      - "8080:8080"
      - "8443:8443"
    environment:
      - ES_HOST= IP ADDRESS
      - ES_PORT= PORT NUMBER
      - ES_USERNAME=elastic
      - ES_PASSWORD=changeme
```

It is working for standalone.xml ( apiman ui ) but not working for apiman.properties and conf-es.config ( vertx gateway) . 

Could you please suggest a way out here ?
