### DISCUSSION TITLE
how to change http redirect to https

### DISCUSSION THREAD

**Discussion by andrewzah** [apiman/apiman#2491] [Help]
I have keycloak running externally.

```yaml
  apiman:
    image: docker.io/ossys/apiman:3.0.0.Final-rocky
    ports:
      - "8085:8080"
    environment:
      APIMAN_AUTH_REALM: 'ossys-dev'
      APIMAN_AUTH_URL: 'https://idp.example.com'
      APIMAN_KC_CLIENT_ID: 'foo'
      APIMAN_KC_CLIENT_PASSWORD: 'bar'
      APIMAN_UI_REDIRECT_URI: 'https://apiman.local/apimanui'
      APIMAN_UI_PROXY_HOST: 'apiman.local'
      APIMAN_UI_PROXY_SCHEME: 'https'
      JAVA_OPTS: "-Xmx1g"
```
but whenever I visit `apiman.local/apimanui`, the redirect url keeps on getting set to `http://apiman.local/`, not `https`.

I've tried setting some properties in `apiman.properties`, like
```
apiman.proxy.scheme=https
apiman.proxy.https-forwarded=true
```
but nothing I've tried so far seems to work, and I can't find documentation on what all of the valid properties are.
