### ISSUE TITLE
Service jboss.deployment.unit."apiman.war".WeldStartService: Failed to start service

### ISSUE THREAD

**Issue by kyagie** [apiman/apiman#2657]
### Apiman Version

3.1.3.Final

### Apiman Manager Distro

WildFly

### Apiman Gateway Distro

Vert.x

### Java Version

Java 17

### Operating System

java 17.0.12 2024-07-16 LTS

### Are you running Apiman in a container, or on an orchestration platform?

Other (please specify below)

### Describe the bug

Unable to start Apiman WildFly. 
`Failed to start service jboss.deployment.unit."apiman.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."apiman.war".WeldStartService: Failed to start service`

### Expected behaviour

Expected Apiman WildFly to start.

### Actual behaviour

Apiman WildFly fails 
<img width="1440" alt="Screenshot 2024-10-15 at 12 42 15" src="https://github.com/user-attachments/assets/813c2284-5ed2-486c-849d-195d5c4598b1">

### How to Reproduce

git clone https://github.com/apiman/apiman.git && cd apiman

./fastbuild.sh

cd tools/server-all/target/docker
docker compose up -d

./wildfly-dev-server/bin/standalone.sh

### Relevant log output

```shell
09:31:47,771 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."apiman.war".WeldStartService: org.jboss.msc.service.StartException in service jboss.deployment.unit."apiman.war".WeldStartService: Failed to start service
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1731)
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1559)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.base/java.lang.Thread.run(Thread.java:842)
Caused by: java.lang.reflect.GenericSignatureFormatError: Signature Parse error: Expected Field Type Signature
	Remaining input: javax.transaction.Transactional$TxType
	at java.base/sun.reflect.generics.parser.SignatureParser.error(SignatureParser.java:124)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:291)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseFieldTypeSignature(SignatureParser.java:277)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSignature(SignatureParser.java:469)
	at java.base/sun.reflect.generics.parser.SignatureParser.parseTypeSig(SignatureParser.java:188)
	at java.base/sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:438)
	at java.base/sun.reflect.annotation.AnnotationParser.parseEnumValue(AnnotationParser.java:473)
	at java.base/sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:344)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:282)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:121)
	at java.base/sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:73)
	at java.base/java.lang.reflect.Executable.declaredAnnotations(Executable.java:625)
	at java.base/java.lang.reflect.Executable.declaredAnnotations(Executable.java:623)
	at java.base/java.lang.reflect.Executable.getDeclaredAnnotations(Executable.java:611)
	at java.base/java.lang.reflect.Method.getDeclaredAnnotations(Method.java:747)
	at java.base/java.lang.reflect.AccessibleObject.getAnnotations(AccessibleObject.java:549)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.resources.HotspotReflectionCache.internalGetAnnotations(HotspotReflectionCache.java:58)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.resources.DefaultReflectionCache.lambda$new$0(DefaultReflectionCache.java:40)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$new$0(ReentrantMapBackedComputingCache.java:55)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:72)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.resources.DefaultReflectionCache.getAnnotations(DefaultReflectionCache.java:75)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.annotated.slim.backed.BackedAnnotated.getAnnotations(BackedAnnotated.java:36)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.annotated.enhanced.jlr.EnhancedAnnotatedMethodImpl.of(EnhancedAnnotatedMethodImpl.java:61)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.annotated.enhanced.jlr.EnhancedAnnotatedTypeImpl.<init>(EnhancedAnnotatedTypeImpl.java:224)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.annotated.enhanced.jlr.EnhancedAnnotatedTypeImpl.of(EnhancedAnnotatedTypeImpl.java:134)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.resources.ClassTransformer$TransformSlimAnnotatedTypeToEnhancedAnnotatedType.apply(ClassTransformer.java:93)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.resources.ClassTransformer$TransformSlimAnnotatedTypeToEnhancedAnnotatedType.apply(ClassTransformer.java:90)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.lambda$new$0(ReentrantMapBackedComputingCache.java:55)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.LazyValueHolder$1.computeValue(LazyValueHolder.java:32)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.LazyValueHolder.get(LazyValueHolder.java:46)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.util.cache.ReentrantMapBackedComputingCache.getValue(ReentrantMapBackedComputingCache.java:72)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.resources.ClassTransformer.getEnhancedAnnotatedType(ClassTransformer.java:251)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.resources.ClassTransformer.getEnhancedAnnotatedType(ClassTransformer.java:232)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.SubclassedComponentInstantiator.initEnhancedSubclass(SubclassedComponentInstantiator.java:86)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.SubclassedComponentInstantiator.<init>(SubclassedComponentInstantiator.java:79)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.SubclassedComponentInstantiator.forInterceptedDecoratedBean(SubclassedComponentInstantiator.java:63)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.BeanInjectionTarget.initializeAfterBeanDiscovery(BeanInjectionTarget.java:121)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.InjectionTargetInitializationContext.initialize(InjectionTargetInitializationContext.java:42)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.injection.producer.InjectionTargetService.initialize(InjectionTargetService.java:63)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bootstrap.WeldStartup.deployBeans(WeldStartup.java:481)
	at org.jboss.weld.core@3.1.6.Final//org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:86)
	at org.jboss.as.weld@23.0.2.Final//org.jboss.as.weld.WeldStartService.start(WeldStartService.java:97)
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1739)
	at org.jboss.msc@1.4.12.Final//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1701)
	... 6 more

09:31:47,774 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "apiman.war")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"apiman.war\".WeldStartService" => "Failed to start service
    Caused by: java.lang.reflect.GenericSignatureFormatError: Signature Parse error: Expected Field Type Signature
	Remaining input: javax.transaction.Transactional$TxType"}}
```

**Comment by msavy** [comment]
Please try building and deploying with Java 11. The version of WildFly doesn't support Java 17.

**Comment by kyagie** [comment]
I have downgraded to `Java 11 `but now Keycloak will not spin up when started with Docker. 
Please check this out. 

**The Error:**
<img width="721" alt="Screenshot 2024-10-15 at 14 06 28" src="https://github.com/user-attachments/assets/3fe58747-4350-4b94-b6bc-bdedc7429b8d">

**Docker Compose File:**
```
services:
  keycloak:
    container_name: keycloak_server_all
    image: quay.io/keycloak/keycloak:18.0.2 # replaced during build, see in target
    # image: quay.io/keycloak/keycloak:26.0.0
    # ./bin/kc.sh build => build and deploy custom themes, providers, etc.
    # ./bin/kc.sh start-dev --import-realm => import Apiman realm, if not already imported.
    entrypoint: ['/bin/bash', '-c']
    command:
      - |
        cd /opt/keycloak
        ./bin/kc.sh build
        ./bin/kc.sh start-dev --import-realm --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
```

**Comment by kyagie** [comment]
> Please try building and deploying with Java 11. The version of WildFly doesn't support Java 17.

I have downgraded to `Java 11` but now **Keycloak** will not spin up when started with Docker.
Please check this out.

Docker Compose File:
```
services:
  keycloak:
    container_name: keycloak_server_all
    image: quay.io/keycloak/keycloak:18.0.2 # replaced during build, see in target
    # image: quay.io/keycloak/keycloak:26.0.0
    # ./bin/kc.sh build => build and deploy custom themes, providers, etc.
    # ./bin/kc.sh start-dev --import-realm => import Apiman realm, if not already imported.
    entrypoint: ['/bin/bash', '-c']
    command:
      - |
        cd /opt/keycloak
        ./bin/kc.sh build
        ./bin/kc.sh start-dev --import-realm --spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true
```
